// Generated by CoffeeScript 1.3.1
(function() {
  var app, express, http, path, server;

  express = require('express');

  http = require('http');

  path = require('path');

  app = express();

  app.configure(function() {
    app.set('port', process.env.PORT || 3333);
    app.set('views', __dirname + '/views');
    app.set('view engine', 'jade');
    app.use(express.favicon());
    app.use(express.logger('dev'));
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express["static"](path.join(__dirname, 'public')));
    app.set('socket.io host', process.env.IO_HOST || 'localhost');
    return app.set('socket.io port', process.env.IO_PORT || 3000);
  });

  app.configure('development', function() {
    return app.use(express.errorHandler());
  });

  app.configure('production', function() {
    return app.set('port', process.env.PORT || 80);
  });

  app.get('/', function(err, res) {
    return res.render('index', {
      title: 'leChat : awesome chat client',
      io_host: app.get('socket.io host'),
      io_port: app.get('socket.io port')
    });
  });

  server = http.createServer(app);

  module.exports = {
    startServer: function() {
      return server.listen(app.get('port'), function() {
        return console.log("Express server listening on port " + (app.get('port')));
      });
    }
  };

}).call(this);
